# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6255af2a40715137ee91600ab85e516744e0ac12c0a33280c8e7fce5c4155e3d8c33d4385c3a1774acae93b32c378877a100aea522e5418d58468893ad1b89eb

test:
  secret_key_base: 7f4d405d2a689c46ac629fff3699d814fbfb3437cc46d0539b24f88f3e5b09d4d5a80da554d149d83856cda97554557ce3bdb135a9192dc4c189a5ef2fc1f4fe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
